### PR TITLE
Improve internals (docs & style)

### PR DESCRIPTION
**Pull request by finnwoelm-sdsn**
Hi @Sakala85 & @DonTouzi,

I configured the ESDoc a bit and will set up the Netlify hosting soon (so we have the API docs online).

I also set up a *pre-commit hook*, that runs prettier and ESLint (finds issues in code) whenever you hit git commit. Could you pull this branch, run `npm ci`, add a random file, and then try to make a commit? I just want to make sure that it works on your computer/OS, too.

You might see this issue:
image

That means it's working :)

(We can also do this together later this week at some point, it's not urgent)

### CODE REVIEW

**Comment by DonTouzi** [comment]
Yes, i prefer to do it all together, very nice by the way :)

**Comment by finnwoelm-sdsn** [comment]
Hi @DonTouzi, could you check one more time if it works now? 😁

**Comment by DonTouzi** [comment]
> Hi @DonTouzi, could you check one more time if it works now? grO,

**Comment by DonTouzi** [comment]
> Hi @DonTouzi, could you check one more time if it works now? grin

yes now

**Comment by DonTouzi** [comment]
> Hi @DonTouzi, could you check one more time if it works now? grin

Hi @finnwoelm-sdsn, it works greatly :) good work

**Pull request merged**
